# doc: https://docs.streamlit.io/library/advanced-features/theming

[server]
folderWatchBlacklist = ['.idea', '.run']
runOnSave = true
port = 8502
cookieSecret = "a-random-key-appears-here"
baseUrlPath = ""
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 1024 #mb
maxMessageSize = 200 #mb
enableWebsocketCompression = true

enableStaticServing = true
#served in ./static :=/app/static/filename.jpg
[theme]
primaryColor = "#fff"
backgroundColor = "#000000"
secondaryBackgroundColor = "#252B48"
textColor = "#ffffff"
font = "sans serif"

[browser]

serverAddress = "localhost"
gatherUsageStats = true
serverPort = 8502

[mapbox]
# Mapbox token: prefer setting the MAPBOX_API_KEY environment variable
# or passing api_keys to pydeck. The token field is deprecated and will be
# removed in future Streamlit versions.
# token = ""


# Removed deprecated/invalid options: Streamlit no longer recognizes several
# of the [deprecation] and [runner] options. If you need similar behavior,
# manage it from code or environment variables. Keeping this file minimal
# avoids runtime warnings about invalid config keys.
